### ISSUE TITLE
tox bootstrap fails

### ISSUE THREAD

**Issue by Elamraoui-Sohayb** [ionelmc/cookiecutter-pylibrary#218]
Hello, 

 I am just trying to run the Readme example with the default values:
`cookiecutter gh:ionelmc/cookiecutter-pylibrary
`
And it fails at the start. 
Pretty sure it's something very simple, but i can't seem to figure it out.
Thanks in advance for the help

```

> ERROR:   bootstrap: InvocationError for command 'c:\programdata\anaconda3\envs\kaggle\python.exe' -m virtualenv --no-download --python 'c:\
programdata\anaconda3\envs\kaggle\python.exe' bootstrap (exited with code 1)
Re-executing with: D:\Git_Learning\pytestmar\python-nameless\.tox\bootstrap\Scripts\python.exe + exec D:\Git_Learning\pytestmar\python-nameless\.tox\bootstrap\Scripts\python.exe ci\bootstrap.py --no-env
Traceback (most recent call last):
  File "ci\bootstrap.py", line 86, in <module>
    exec_in_env()
  File "ci\bootstrap.py", line 48, in exec_in_env
    os.execv(python_executable, [python_executable, __file__, "--no-env"])
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "C:\Users\elamr\AppData\Local\Temp\tmpvjwmfv0s.py", line 50, in <module>
    subprocess.check_call(['tox', '-e', 'bootstrap'])
  File "c:\programdata\anaconda3\envs\kaggle\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tox', '-e', 'bootstrap']' returned non-zero exit status 1.

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\elamr\AppData\Local\Temp\tmpvjwmfv0s.py", line 53, in <module>
    subprocess.check_call([sys.executable, '-mtox', '-e', 'bootstrap'])
  File "c:\programdata\anaconda3\envs\kaggle\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\programdata\\anaconda3\\envs\\kaggle\\python.exe', '-mtox', '-e', 'bootstrap']' returned non-zero exit status 1.

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\elamr\AppData\Local\Temp\tmpvjwmfv0s.py", line 55, in <module>
    subprocess.check_call([sys.executable, join('ci', 'bootstrap.py')])
  File "c:\programdata\anaconda3\envs\kaggle\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\programdata\\anaconda3\\envs\\kaggle\\python.exe', 'ci\\bootstrap.py']' returned non-zero exit status 1.
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

```

**Comment by ionelmc** [comment]
You need to have [tox](https://tox.readthedocs.io/) available on PATH for this project to work.

**Comment by Elamraoui-Sohayb** [comment]
Thanks, that fixed it!
