### ISSUE TITLE
TemplateNotFound: .github\workflows\github-actions.yml

### ISSUE THREAD

**Issue by veleek** [ionelmc/cookiecutter-pylibrary#239]
When running `cookiecutter gh:ionelmc/cookiecutter-pylibrary` I get the following error while trying to bootstrap the CI stuff.

```
####################################################### Generating CI configuration ########################################################
bootstrap: install_deps> python -I -m pip install jinja2 tox
bootstrap: commands[0]> python ci/bootstrap.py --no-env
Project path: C:\src\github\veleek\py-sleepme2\py-sleepme
Traceback (most recent call last):
  File "C:\src\github\veleek\py-sleepme2\py-sleepme\ci\bootstrap.py", line 78, in <module>
    main()
  File "C:\src\github\veleek\py-sleepme2\py-sleepme\ci\bootstrap.py", line 70, in main
    destination.write_text(jinja.get_template(template_path).render(tox_environments=tox_environments))
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 195, in get_source
    pieces = split_template_path(template)
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 36, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .github\workflows\github-actions.yml
bootstrap: exit 1 (1.30 seconds) C:\src\github\veleek\py-sleepme2\py-sleepme> python ci/bootstrap.py --no-env pid=41760
  bootstrap: FAIL code 1 (5.44=setup[4.14]+cmd[1.30] seconds)
  evaluation failed :( (5.64 seconds)
bootstrap: commands[0]> python ci/bootstrap.py --no-env
Project path: C:\src\github\veleek\py-sleepme2\py-sleepme
Traceback (most recent call last):
  File "C:\src\github\veleek\py-sleepme2\py-sleepme\ci\bootstrap.py", line 78, in <module>
    main()
  File "C:\src\github\veleek\py-sleepme2\py-sleepme\ci\bootstrap.py", line 70, in main
    destination.write_text(jinja.get_template(template_path).render(tox_environments=tox_environments))
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 195, in get_source
    pieces = split_template_path(template)
  File "C:\Users\veleek\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\loaders.py", line 36, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .github\workflows\github-actions.yml
bootstrap: exit 1 (0.80 seconds) C:\src\github\veleek\py-sleepme2\py-sleepme> python ci/bootstrap.py --no-env pid=28396
  bootstrap: FAIL code 1 (0.80=setup[0.00]+cmd[0.80] seconds)
  evaluation failed :( (1.00 seconds)
Re-executing with: C:\src\github\veleek\py-sleepme2\py-sleepme\.tox\bootstrap\Scripts\python.exe
+ exec C:\src\github\veleek\py-sleepme2\py-sleepme\.tox\bootstrap\Scripts\python.exe C:\src\github\veleek\py-sleepme2\py-sleepme\ci\bootstrap.py --no-env```

**Comment by veleek** [comment]
Wow, definitely the fastest that I have EVER had an issue resolved. :D  

Just came back to provide a workaround and looks like it's not necessary!  Amazing!
