### ISSUE TITLE
Docs fail to build under Sphinx 1.4

### ISSUE THREAD

**Issue by seanfisk** [ionelmc/cookiecutter-pylibrary#54]
I decided to give this template a try today! Coincidentally, [Sphinx 1.4](http://www.sphinx-doc.org/en/stable/changes.html#release-1-4-released-mar-28-2016) was also released today. Sphinx 1.4 introduces some incompatible changes, including removal of the hard dependency on `sphinx_rtd_theme`. This is currently causing the build to fail:

```
$ tox -e docs
GLOB sdist-make: /Users/sean/tmp/cookie-sphinx/python-nameless/setup.py
docs create: /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs
docs installdeps: -r/Users/sean/tmp/cookie-sphinx/python-nameless/docs/requirements.txt
docs inst: /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/dist/nameless-0.1.0.zip
docs installed: alabaster==0.7.7,Babel==2.2.0,docutils==0.12,imagesize==0.7.0,Jinja2==2.8,MarkupSafe==0.23,nameless==0.1.0,Pygments==2.1.3,pytz==2016.3,six==1.10.0,snowballstemmer==1.2.1,Sphinx==1.4
docs runtests: PYTHONHASHSEED='3980784878'
docs runtests: commands[0] | sphinx-build -E -b html docs dist/docs
Running Sphinx v1.4
making output directory...

Exception occurred:
  File "conf.py", line 41, in <module>
ImportError: No module named sphinx_rtd_theme
The full traceback has been saved in /var/folders/mj/nmpw6v8s15z_cj39dmv0fk9m0000gn/T/sphinx-err-_FW4dq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ERROR: InvocationError: '/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/bin/sphinx-build -E -b html docs dist/docs'
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
```
I chose all of the defaults in creating the sample project.

##### Environment:

OS: OS X 10.10 Yosemite
Python: tox run by CPython 3.5.1, docs built by CPython 2.7.11
I use [pyenv](https://github.com/yyuu/pyenv) to manage my Pythons.

As reported by Python:
3.5.1:
```
platform.platform(): Darwin-14.5.0-x86_64-i386-64bit
platform.mac_ver(): ('10.10.5', ('', '', ''), 'x86_64')
platform.python_compiler(): GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)
platform.python_implementation(): CPython
platform.python_version(): 3.5.1
platform.architecture(): ('64bit', '')
```
2.7.11:
```
platform.platform(): Darwin-14.5.0-x86_64-i386-64bit
platform.mac_ver(): ('10.10.5', ('', '', ''), 'x86_64')
platform.python_compiler(): GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)
platform.python_implementation(): CPython
platform.python_version(): 2.7.11
platform.architecture(): ('64bit', '')
```

Thanks for creating this template!

**Comment by seanfisk** [comment]
**Update:** After applying #55, the docs build is failing here:
```
$ tox -e docs
GLOB sdist-make: /Users/sean/tmp/cookie-sphinx/python-nameless/setup.py
docs inst-nodeps: /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/dist/nameless-0.1.0.zip
docs installed: alabaster==0.7.7,Babel==2.2.0,docutils==0.12,imagesize==0.7.0,Jinja2==2.8,MarkupSafe==0.23,nameless==0.1.0,Pygments==2.1.3,pytz==2016.3,six==1.10.0,snowballstemmer==1.2.1,Sphinx==1.4,sphinx-rtd-theme==0.1.9
docs runtests: PYTHONHASHSEED='1440827637'
docs runtests: commands[0] | sphinx-build -E -b html docs dist/docs
Running Sphinx v1.4
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 9 source files that are out of date
updating environment: 9 added, 0 changed, 0 removed
reading sources... [ 11%] authors
reading sources... [ 22%] changelog
reading sources... [ 33%] contributing
reading sources... [ 44%] index
reading sources... [ 55%] installation
reading sources... [ 66%] readme
reading sources... [ 77%] reference/index
reading sources... [ 88%] reference/nameless
reading sources... [100%] usage

README.rst:11: WARNING: nonlocal image URI found: https://readthedocs.org/projects/python-nameless/badge/?style=flat
README.rst:0: WARNING: nonlocal image URI found: https://travis-ci.org/ionelmc/python-nameless.svg?branch=master
README.rst:0: WARNING: nonlocal image URI found: https://ci.appveyor.com/api/projects/status/github/ionelmc/python-nameless?branch=master&svg=true
README.rst:0: WARNING: nonlocal image URI found: https://requires.io/github/ionelmc/python-nameless/requirements.svg?branch=master
README.rst:0: WARNING: nonlocal image URI found: https://codecov.io/github/ionelmc/python-nameless/coverage.svg?branch=master
README.rst:16: WARNING: nonlocal image URI found: https://img.shields.io/pypi/v/nameless.svg?style=flat
README.rst:16: WARNING: nonlocal image URI found: https://img.shields.io/pypi/dm/nameless.svg?style=flat
README.rst:16: WARNING: nonlocal image URI found: https://img.shields.io/pypi/wheel/nameless.svg?style=flat
README.rst:16: WARNING: nonlocal image URI found: https://img.shields.io/pypi/pyversions/nameless.svg?style=flat
README.rst:16: WARNING: nonlocal image URI found: https://img.shields.io/pypi/implementation/nameless.svg?style=flat
README.rst:18: WARNING: nonlocal image URI found: https://readthedocs.org/projects/python-nameless/badge/?style=flat
README.rst:22: WARNING: nonlocal image URI found: https://travis-ci.org/ionelmc/python-nameless.svg?branch=master
README.rst:26: WARNING: nonlocal image URI found: https://ci.appveyor.com/api/projects/status/github/ionelmc/python-nameless?branch=master&svg=true
README.rst:30: WARNING: nonlocal image URI found: https://requires.io/github/ionelmc/python-nameless/requirements.svg?branch=master
README.rst:34: WARNING: nonlocal image URI found: https://codecov.io/github/ionelmc/python-nameless/coverage.svg?branch=master
README.rst:38: WARNING: nonlocal image URI found: https://img.shields.io/pypi/v/nameless.svg?style=flat
README.rst:42: WARNING: nonlocal image URI found: https://img.shields.io/pypi/dm/nameless.svg?style=flat
README.rst:46: WARNING: nonlocal image URI found: https://img.shields.io/pypi/wheel/nameless.svg?style=flat
README.rst:50: WARNING: nonlocal image URI found: https://img.shields.io/pypi/pyversions/nameless.svg?style=flat
README.rst:54: WARNING: nonlocal image URI found: https://img.shields.io/pypi/implementation/nameless.svg?style=flat
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 11%] authors
writing output... [ 22%] changelog
writing output... [ 33%] contributing
writing output... [ 44%] index
writing output... [ 55%] installation
writing output... [ 66%] readme
writing output... [ 77%] reference/index
writing output... [ 88%] reference/nameless
writing output... [100%] usage

generating indices... genindex
Exception occurred:
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/themes/basic/genindex-single.html", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack
The full traceback has been saved in /var/folders/mj/nmpw6v8s15z_cj39dmv0fk9m0000gn/T/sphinx-err-Xij9Gn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ERROR: InvocationError: '/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/bin/sphinx-build -E -b html docs dist/docs'
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
```
Full traceback:
```
# Sphinx version: 1.4
# Python version: 2.7.11 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   writing output... [ 33%] contributing
#   writing output... [ 44%] index
#   writing output... [ 55%] installation
#   writing output... [ 66%] readme
#   writing output... [ 77%] reference/index
#   writing output... [ 88%] reference/nameless
#   writing output... [100%] usage
#   
#   generating indices...
#   genindex
# Loaded extensions:
#   sphinx.ext.coverage (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/coverage.pyc
#   alabaster (0.7.7) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.autosummary (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/autosummary/__init__.pyc
#   sphinx.ext.doctest (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/doctest.pyc
#   sphinx.ext.ifconfig (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/ifconfig.pyc
#   sphinx.ext.autodoc (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.napoleon (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/napoleon/__init__.pyc
#   sphinx.ext.viewcode (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.todo (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.extlinks (1.4) from /Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/ext/extlinks.pyc
Traceback (most recent call last):
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/application.py", line 287, in build
    self.builder.build_update()
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 325, in build
    self.finish()
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/builders/html.py", line 461, in finish
    self.finish_tasks.add_task(self.gen_indices)
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/util/parallel.py", line 40, in add_task
    res = task_func()
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/builders/html.py", line 477, in gen_indices
    self.write_genindex()
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/builders/html.py", line 535, in write_genindex
    'genindex-single.html')
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/builders/html.py", line 802, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/jinja2glue.py", line 138, in render
    return self.environment.get_template(template).render(context)
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/themes/basic/genindex-single.html", line 32, in top-level template code
    {% set title = _('Index') %}
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx_rtd_theme/layout.html", line 150, in top-level template code
    {% block body %}{% endblock %}
  File "/Users/sean/tmp/cookie-sphinx/python-nameless/.tox/docs/lib/python2.7/site-packages/sphinx/themes/basic/genindex-single.html", line 40, in block "body"
    {%- for entryname, (links, subitems) in column %}
ValueError: too many values to unpack
```
The problem appears to be with the index. Returning `html_split_index` in `docs/conf.py` to its default of `True` allows the build to complete successfully, but that's all I've been able to ascertain as of now. A split index appears to work fine with a blank Sphinx 1.4 project (generated with `sphinx-quickstart`), so the problem will require a little more debugging.

Thanks, and sorry for all the posts today :neutral_face:

**Comment by ionelmc** [comment]
Here it say `True` is the default: http://www.sphinx-doc.org/en/stable/config.html#confval-html_split_index

It looks like added a broken change: https://github.com/sphinx-doc/sphinx/pull/2396

**Comment by seanfisk** [comment]
@ionelmc Ah, you're right about that bug! Also, your pull request title was priceless :grinning:

**Comment by ionelmc** [comment]
Ok so they are quite slow to release the fix ...

I've got some time to check what that option actually does, and I don't think we should have `True` as default anyway. Changed in https://github.com/ionelmc/cookiecutter-pylibrary/commit/7dbbdd13972733e034b335a9ea177849d0591ecd.

**Comment by seanfisk** [comment]
@ionelmc Sounds good to me! Thanks :+1:
