### ISSUE TITLE
Configurable nosetests support

### ISSUE THREAD

**Issue by svetlyak40wt** [ionelmc/cookiecutter-pylibrary#8]
I want to contribute a nosetests support. What is the best way to make choice between py.test and nose configurable?

**Comment by ionelmc** [comment]
I would involve:

* Adding an option for it (and default to pytest) in https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/cookiecutter.json#L17
* Adding it in the cookiecutter test builder suite https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/ci/setup.cfg#L1
* Run `./ci/bootstrap.sh` to regenerate the test .cookiecutterrc files.
* Changing the bare tox.ini to have an conditional for it, eg https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/tox.ini#L43-L45
* Changing the template tox.ini (don't forget the raw sections) to have an conditional for it, eg https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/ci/templates/tox.ini#L20-L24 (this tox.ini file is used with the test_matrix_configurator=yes option)

Then just push branch and make PR (Travis will run the tests) and we'll figure out what to do from there.

**Comment by ionelmc** [comment]
If you get stuck, just make the PR with whatever you have so far.

**Comment by svetlyak40wt** [comment]
Thank, you. Will send a pull request.

**Comment by svetlyak40wt** [comment]
@ionelmc here is a pull: https://github.com/ionelmc/cookiecutter-pylibrary/pull/9
What is the best way to test if it works correctly?

**Comment by ionelmc** [comment]
If you wanna test locally you can run `cookiecutter path/to/your/fork`.

You can also run the whole suite (just run `tox`), but be warned, it will override your `~/.cookiecutterrc` - I will fix that soon-ish.

**Comment by svetlyak40wt** [comment]
@ionelmc could you please help me with tox?

I tried to run it locally, but have got this strange error:

```
test create: /Users/art/projects/cookiecutter-pylibrary/.tox/test
test installdeps: cookiecutter==1.0.0, bumpversion==0.5.1, tox==1.9.0
test runtests: PYTHONHASHSEED='2864253310'
test runtests: commands[0] | /Users/art/projects/cookiecutter-pylibrary/ci/test.cmd matrix-nosetests
ERROR: invocation failed (errno 13), args: ['/Users/art/projects/cookiecutter-pylibrary/ci/test.cmd', 'matrix-nosetests'], cwd: /Users/art/projects/cookiecutter-pylibrary
Traceback (most recent call last):
  File "/Users/art/.local/bin/tox", line 9, in <module>
    load_entry_point('tox==1.8.1', 'console_scripts', 'tox')()
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_cmdline.py", line 26, in main
    retcode = Session(config).runcommand()
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_cmdline.py", line 310, in runcommand
    return self.subcommand_test()
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_cmdline.py", line 455, in subcommand_test
    self.runtestenv(venv)
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_cmdline.py", line 463, in runtestenv
    venv.test(redirect=redirect)
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_venv.py", line 347, in test
    self._pcall(argv, cwd=cwd, action=action, redirect=redirect)
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_venv.py", line 370, in _pcall
    return action.popen(args, cwd=cwd, env=env, redirect=redirect)
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_cmdline.py", line 97, in popen
    stdout=f, stderr=STDOUT)
  File "/Users/art/.local/venvs/tox/lib/python2.7/site-packages/tox/_cmdline.py", line 159, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

As I understand, `cookiecutter-pylibrary/ci/test.cmd` is a script for windows environment, right? Why it is executed on OSX?

**Comment by ionelmc** [comment]
My bad, I accidentally unset the exec perms on that file. Run `chmod +x ci/test.cmd` to fix.

`test.cmd` is just a shim (can run as both windows batch or unix shell).

**Comment by ionelmc** [comment]
Seems I also have the wrong slash inside (should be `ci/test.sh` instead of `ci\test.sh`).
